name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-lilo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven and format check
        run: mvn -B -ntp package com.spotify.fmt:fmt-maven-plugin:2.21.1:check -Denforcer.skip

  check-samples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build lilo and cache
        run: mvn -B -ntp clean install -DskipTests -Dgpg.skip -Dcheckstyle.skip -Denforcer.skip -Dmaven.javadoc.skip -Dmaven.source.skip

      - name: Check lilo samples
        run: cd samples && mvn -B -ntp compile com.spotify.fmt:fmt-maven-plugin:2.21.1:check
