name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-lilo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp package

      - name: Format Check
        run: mvn -B -ntp com.spotify.fmt:fmt-maven-plugin:2.21.1:check

  check-lilo-samples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: cd lilo-samples && mvn -B -ntp package

      - name: Format Check
        run: cd lilo-samples && mvn -B -ntp com.spotify.fmt:fmt-maven-plugin:2.21.1:check
